export const RARITIES = {
  fallback: { label: "Fallback", weight: 0, price: 0 },
  common: { label: "Common", weight: 60, price: 17 },
  uncommon: { label: "Uncommon", weight: 27, price: 34 },
  rare: { label: "Rare", weight: 10, price: 56 },
  legendary: { label: "Legendary", weight: 3, price: 122 },
};
// Imported from data/catalog/*.csv; IDs and wording follow the source sheets.
export const TRINKETS = [
  {
    id: "even",
    name: "Even",
    emoji: "⚖️",
    rarity: "common",
    effect: "even",
    description: "Score 4 points for each even digit.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "odd",
    name: "Odd Duck",
    emoji: "🦆",
    rarity: "common",
    effect: "odd",
    description: "Score 4 points for each odd digit.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "pair",
    name: "Cherries",
    emoji: "🍒",
    rarity: "common",
    effect: "pair",
    description: "Score 8 points for each pair of digits.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "high",
    name: "Head in the Clouds",
    emoji: "😶‍🌫️",
    rarity: "common",
    effect: "high",
    description: "Score 3 points for each digit that is 5 or higher.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "low",
    name: "Small Fry",
    emoji: "🍟",
    rarity: "common",
    effect: "low",
    description: "Score 6 points for each digit lower than 4.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "sum",
    name: "Pocket Change",
    emoji: "🪙",
    rarity: "common",
    effect: "sum",
    description: "Score the sum of all 6 digits.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "sandwich",
    name: "Sandwich",
    emoji: "🥪",
    rarity: "uncommon",
    effect: "sandwich",
    description:
      "Score 35 points for each 3-digit sandwich (first and last digit are the same.)",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "brainrot1",
    name: "Brainrot I",
    emoji: "🥀",
    rarity: "uncommon",
    effect: "brainrot1",
    description: "Score 67 points if you have a 6 and a 7.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "seven",
    name: "Lucky Seven",
    emoji: "🎰",
    rarity: "uncommon",
    effect: "seven",
    description: "Every 7 increases the points I give on every spin by 7.",
    kind: "trinket",
    metadata: {
      power: 0,
    },
  },
  {
    id: "bookends",
    name: "Bookends",
    emoji: "📖",
    rarity: "uncommon",
    effect: "bookends",
    description: "Score 50 points if the first and last digits match.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "rainbow",
    name: "Rainbow",
    emoji: "🌈",
    rarity: "uncommon",
    effect: "rainbow",
    description: "Score 9 points for each different digit.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "triple",
    name: "Hat Trick",
    emoji: "⚽",
    rarity: "rare",
    effect: "triple",
    description: "Score 100 points for every group of three matching digits.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "miniflush",
    name: "Mini-Flush",
    emoji: "🧻",
    rarity: "rare",
    effect: "miniflush",
    description: "Score 200 points if you have 4 of the same number.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "flush",
    name: "Flush",
    emoji: "🚽",
    rarity: "rare",
    effect: "flush",
    description: "Score 500 points if you have 5 of the same number.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "brainrot2",
    name: "Brainrot II",
    emoji: "💀",
    rarity: "rare",
    effect: "brainrot2",
    description: "Score 167 points if you have a 6 and then 7, in that order.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "brainrot3",
    name: "Brainrot III",
    emoji: "🤷",
    rarity: "legendary",
    effect: "brainrot3",
    description: "Score 670 points if you only have 6s or 7s.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "mining",
    name: "Pickaxe",
    emoji: "⛏️",
    rarity: "uncommon",
    effect: "mining",
    description:
      "Increases the chance of Rares and Legendaries in the shop by 25%.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "magnifier",
    name: "Magnifying Glass",
    emoji: "🔍",
    rarity: "rare",
    effect: "magnifier",
    description:
      "Increases the chance of Rares and Legendaries in the shop by 50%.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "detective",
    name: "Detective",
    emoji: "🕵️",
    rarity: "legendary",
    effect: "detective",
    description:
      "Score 10,000 points if you score the most common password (123456, in order).",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "pig",
    name: "Piggy Bank",
    emoji: "🐖",
    rarity: "common",
    effect: "pig",
    description: "Gain $8 after each spin.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "stocks",
    name: "Stonks",
    emoji: "💹",
    rarity: "uncommon",
    effect: "stocks",
    description: "Gain $20 after each spin.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "nerd",
    name: "Nerd",
    emoji: "🤓",
    rarity: "legendary",
    effect: "nerd",
    description: "Score 42 points and gain $10 for each 0 or 1 I score.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "hotface",
    name: "Heat Miser",
    emoji: "🥵",
    rarity: "uncommon",
    effect: "hotface",
    description:
      "Every warm number (8,9,0,1,2) increases the points I give on every spin by 2.",
    kind: "trinket",
    metadata: {
      power: 0,
    },
  },
  {
    id: "coldface",
    name: "Cold Miser",
    emoji: "🥶",
    rarity: "uncommon",
    effect: "coldface",
    description:
      "Every cold number (3,4,5,6,7) increases the points I give on every spin by 2.",
    kind: "trinket",
    metadata: {
      power: 0,
    },
  },
  {
    id: "eightball",
    name: "Eight Ball",
    emoji: "🎱",
    rarity: "rare",
    effect: "eightball",
    description: "Trinkets activate on 8s twice.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "realknife",
    name: "The Real Knife",
    emoji: "🔪",
    rarity: "rare",
    effect: "realknife",
    description:
      "Every nine 9s you see guarantees a Legendary Trinket in the next shop and gives you $99.",
    kind: "trinket",
    metadata: {
      count: 0,
    },
  },
  {
    id: "hundred",
    name: "100",
    emoji: "💯",
    rarity: "uncommon",
    effect: "hundred",
    description: "Score 100 points if your number ends in two zeroes.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "cross",
    name: "The Cross",
    emoji: "✝️",
    rarity: "uncommon",
    effect: "cross",
    description: "Greatly reduce the chance to see the number 6.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "ministraight",
    name: "Mini Straight",
    emoji: "📎",
    rarity: "rare",
    effect: "ministraight",
    description:
      "If you have 3 numbers in a row that go sequentially up or down, score the product of those numbers.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "straight",
    name: "Straight",
    emoji: "📏",
    rarity: "rare",
    effect: "straight",
    description:
      "If you have 4 or more numbers in a row that go sequentially up or down, score the product of those numbers.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "graduate",
    name: "Graduate",
    emoji: "🧑‍🎓",
    rarity: "uncommon",
    effect: "graduate",
    description: "Increases your chance to see Rare and Legendary tools.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "bearmarket",
    name: "Bear Market",
    emoji: "📉",
    rarity: "uncommon",
    effect: "bearmarket",
    description:
      "If your last number is lower than your first number, gain $20 and score 40 points.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "bullmaket",
    name: "Bull Market",
    emoji: "📈",
    rarity: "uncommon",
    effect: "bullmaket",
    description:
      "If your last number is higher than your first number, gain $20 and score 40 points.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "rabbit",
    name: "Rabbit",
    emoji: "🐇",
    rarity: "legendary",
    effect: "rabbit",
    description:
      "I give 177 points each spin. If your final number is divisible by 7, permanently increase the points I give by 177.",
    kind: "trinket",
    metadata: {
      power: 177,
    },
  },
  {
    id: "crystalball",
    name: "Crystal Ball",
    emoji: "🔮",
    rarity: "legendary",
    effect: "crystalball",
    description:
      "When you see eight 8s, gain a random trinket (ignores rarities).",
    kind: "trinket",
    metadata: {
      count: 0,
    },
  },
  {
    id: "heaven",
    name: "11th Heaven",
    emoji: "🌤️",
    rarity: "legendary",
    effect: "heaven",
    description:
      "I give 11 points each spin. If your final number is divisible by 11, permanently double the points I give.",
    kind: "trinket",
    metadata: {
      power: 11,
    },
  },
  {
    id: "three",
    name: "The Number 3",
    emoji: "3️⃣",
    rarity: "uncommon",
    effect: "three",
    description:
      "I give 13 points each spin. If your final number is divisible by 3, permanently increase the points I give by 13.",
    kind: "trinket",
    metadata: {
      power: 13,
    },
  },
  {
    id: "fortunecookie",
    name: "Fortune Cookie",
    emoji: "🥠",
    rarity: "rare",
    effect: "fortunecookie",
    description:
      "Doubles your points if you have no 4s and have at least one 8.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "snail",
    name: "Snail",
    emoji: "🐌",
    rarity: "uncommon",
    effect: "snail",
    description:
      "If you don't meet the goal after a spin, gain a random common or uncommon trinket.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "fiver",
    name: "Fiver",
    emoji: "💵",
    rarity: "common",
    effect: "fiver",
    description: "Score 25 points if your number is divisible by 5.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "zero",
    name: "Goose Egg",
    emoji: "🥚",
    rarity: "common",
    effect: "zero",
    description: "Score 12 points for every zero.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "monocle",
    name: "Monocle",
    emoji: "🧐",
    rarity: "legendary",
    effect: "monocle",
    description:
      "If you only have 1 unique digit in your final number, score 1000 points.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "elevator",
    name: "Elevator",
    emoji: "🛗",
    rarity: "common",
    effect: "elevator",
    description:
      "If all your numbers are strictly increasing or decreasing, score 100 points.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "wrench",
    name: "Wrench",
    emoji: "🔧",
    rarity: "uncommon",
    effect: "wrench",
    description: "Tools are 50% cheaper.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "screwdriver",
    name: "Screwdriver",
    emoji: "🪛",
    rarity: "uncommon",
    effect: "screwdriver",
    description: "Tool upgrades are 50% cheaper.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "constructionworker",
    name: "Construction Worker",
    emoji: "👷",
    rarity: "legendary",
    effect: "constructionworker",
    description: "After each spin, gain a random tool upgrade.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "technologist",
    name: "Technologist",
    emoji: "🧑‍💻",
    rarity: "legendary",
    effect: "technologist",
    description: "After each spin, gain a random tool.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "cartwheel",
    name: "Cartwheeler",
    emoji: "🤸",
    rarity: "rare",
    effect: "cartwheel",
    description: "Reroll tools have +3 uses each spin.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "package",
    name: "Mysterious Package",
    emoji: "📦",
    rarity: "rare",
    effect: "package",
    description:
      "Replace all your other trinkets with ones that are one rarity higher.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "bank",
    name: "Bank",
    emoji: "🏦",
    rarity: "common",
    effect: "bank",
    description: "Gain 10% interest when you enter a shop.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "moai",
    name: "Moai",
    emoji: "🗿",
    rarity: "legendary",
    effect: "moai",
    description:
      "Picks a new favorite number when you spin. Multiplies your points this round by 2 EVERY time it scores its favorite number.",
    kind: "trinket",
    metadata: {
      favorite: 0,
    },
  },
  {
    id: "relaxedface",
    name: "Relaxed Face",
    emoji: "☺️",
    rarity: "common",
    effect: "relaxedface",
    description: "Scores +24 points no matter what you spin.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "blackjack",
    name: "Blackjack",
    emoji: "♠️",
    rarity: "common",
    effect: "blackjack",
    description: "If your numbers sum to 21, triple your score this round.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "fullhouse",
    name: "Full House",
    emoji: "🏠",
    rarity: "common",
    effect: "fullhouse",
    description:
      "Double your score this round if you have three of the same digit and two or more of a different digit.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "family",
    name: "The Family",
    emoji: "👪",
    rarity: "rare",
    effect: "family",
    description: "Score 10 times the sum of all your digits.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "bean",
    name: "Bean Counter",
    emoji: "🫘",
    rarity: "common",
    effect: "bean",
    description:
      "Score 1 point for each 1, then increase the number of points I score by 5.",
    kind: "trinket",
    metadata: {
      power: 1,
    },
  },
  {
    id: "dragon",
    name: "Dragon",
    emoji: "🐉",
    rarity: "common",
    effect: "dragon",
    description: "Scores +4 points each spin for each trinket you have.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "wheel",
    name: "Wheel",
    emoji: "🛞",
    rarity: "common",
    effect: "wheel",
    description: "Shop rerolls cost 1 less.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "pairofeyes",
    name: "Pair of Eyes",
    emoji: "👀",
    rarity: "rare",
    effect: "pairofeyes",
    description:
      "If you have two zeroes that aren't next to each other, score 21 times your highest digit.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "bicycle",
    name: "Bicycle",
    emoji: "🚲",
    rarity: "uncommon",
    effect: "bicycle",
    description: "Rerolls cost 2 less.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "apple",
    name: "Apple",
    emoji: "🍎",
    rarity: "common",
    effect: "apple",
    description:
      "Scores 10 points for each pair of numbers you have that sum to 10.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "clover",
    name: "Four-Leaf Clover",
    emoji: "🍀",
    rarity: "common",
    effect: "clover",
    description: "Doubles your chance of rolling a 7.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "octopus",
    name: "Octopus",
    emoji: "🐙",
    rarity: "common",
    effect: "octopus",
    description: "When I see an 8, gain $8.",
    kind: "trinket",
    metadata: {},
    price: 38,
  },
  {
    id: "yinyang",
    name: "Yin & Yang",
    emoji: "☯️",
    rarity: "uncommon",
    effect: "yinyang",
    description:
      "Scores 88 points if you have an equal number of odd and even numbers.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "printer",
    name: "Printer",
    emoji: "🖨️",
    rarity: "legendary",
    effect: "printer",
    description:
      "Every shop adds a copy of one of your trinkets at double price for sale (can't print printers though!).",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "checkered-flag",
    name: "Checkered Flag",
    emoji: "🏁",
    rarity: "rare",
    effect: "checkered-flag",
    description: "If you don't meet the goal, gain enough points to meet it.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "hammer",
    name: "Hammer",
    emoji: "🔨",
    rarity: "rare",
    effect: "hammer",
    description: "Shops have one more tool upgrade.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "backpack",
    name: "Backpack",
    emoji: "🎒",
    rarity: "rare",
    effect: "backpack",
    description: "Shops have one more trinket.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "new moon",
    name: "New Moon",
    emoji: "🌚",
    rarity: "legendary",
    effect: "new moon",
    description: "Multiplies your score by 10 for every grey slot.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "bug",
    name: "Bug",
    emoji: "🐛",
    rarity: "fallback",
    effect: "bug",
    description: "What did you do? (Scores for 2560 points)",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "mechanical-arm",
    name: "Mechanical Arm",
    emoji: "🦾",
    rarity: "rare",
    effect: "mechanical-arm",
    description: "Tool upgrades are much more likely to be Rare or Legendary.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "robot",
    name: "Robot",
    emoji: "🤖",
    rarity: "common",
    effect: "robot",
    description:
      "Scores 101 (5) points every spin. When Robot sees a 0 or 1, permanently increase the points this gives by 10 (2).",
    kind: "trinket",
    metadata: {
      power: 5,
    },
  },
  {
    id: "devil",
    name: "Devil",
    emoji: "😈",
    rarity: "rare",
    effect: "devil",
    description: "Scores 666 points when you score 3 consecutive 6s.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "no-tools",
    name: "No Tools!",
    emoji: "🙅",
    rarity: "common",
    effect: "no-tools",
    description: "If you didn't use any tools this round, score 120 points.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "test-tube",
    name: "Replication Experiment",
    emoji: "🧪",
    rarity: "rare",
    effect: "test-tube",
    description: "Gain a copy of a random trinket you have.",
    kind: "trinket",
    metadata: {},
  },
  {
    id: "alembic",
    name: "Novel Experiment",
    emoji: "⚗️",
    rarity: "rare",
    effect: "alembic",
    description: "Gain a random trinket. (Ignores rarities)",
    kind: "trinket",
    metadata: {},
  },
];
export const TOOLS = [
  {
    id: "reroll",
    name: "Reroll One",
    emoji: "🔄",
    rarity: "common",
    effect: "reroll",
    description: "Select a reel to roll a new random number.",
    kind: "tool",
    maxUses: 3,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "increment",
    name: "Increment",
    emoji: "➕",
    rarity: "common",
    effect: "increment",
    description: "Add 1 to a reel (9 becomes 0)",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "decrement",
    name: "Decrement",
    emoji: "➖",
    rarity: "common",
    effect: "decrement",
    description: "Subtract 1 from a reel (0 becomes 9)",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "flip",
    name: "Flip",
    emoji: "🔃",
    rarity: "common",
    effect: "flip",
    description: "Replace a digit with 9 minus that digit.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "swap",
    name: "Swap",
    emoji: "🔀",
    rarity: "uncommon",
    effect: "swap",
    description: "Pick two different digits to switch.",
    kind: "tool",
    maxUses: 2,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "double",
    name: "Double",
    emoji: "‼️",
    rarity: "uncommon",
    effect: "double",
    description: "Double a digit, keeping only the last digit.",
    kind: "tool",
    maxUses: 2,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "copy",
    name: "Copycat",
    emoji: "🐈",
    rarity: "rare",
    effect: "copy",
    description: "Select a reel to copy, then a different reel to copy onto.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "bigreroll",
    name: "Reroll Three",
    emoji: "🌀",
    rarity: "uncommon",
    effect: "bigreroll",
    description: "Select a reel to reroll, then reroll the reels next to it.",
    kind: "tool",
    maxUses: 2,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "megareroll",
    name: "Reroll All",
    emoji: "😵‍💫",
    rarity: "rare",
    effect: "megareroll",
    description: "Respin all reels.",
    kind: "tool",
    maxUses: 2,
    limitedUse: false,
    target: "all",
  },
  {
    id: "seven-tool",
    name: "Time for Seven",
    emoji: "🕖",
    rarity: "rare",
    effect: "seven-tool",
    description: "Set any reel to 7.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "eight-tool",
    name: "Time for Eight",
    emoji: "🕗",
    rarity: "rare",
    effect: "eight-tool",
    description: "Set any reel to 8.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "echo",
    name: "Speak Facts",
    emoji: "🗣️",
    rarity: "legendary",
    effect: "echo",
    description: "Copy a reel's digit to both its neighbors.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "bomb",
    name: "Bomb",
    emoji: "💣",
    rarity: "rare",
    effect: "bomb",
    description:
      "Permanently replace a reel slot with a Bomb (starting at 3). Landing on a bomb counts it down, and bombs exploding removes the reel slot altogether and gives you +$100!",
    kind: "tool",
    maxUses: 6,
    limitedUse: true,
    target: "reel",
  },
  {
    id: "w",
    name: "W",
    emoji: "🇼",
    rarity: "rare",
    effect: "w",
    description:
      "Permanently replace a reel slot with a W. Landing on a W increases the cash bonus for the round by $50.",
    kind: "tool",
    maxUses: 3,
    limitedUse: true,
    target: "reel",
  },
  {
    id: "camera",
    name: "Camera",
    emoji: "📸",
    rarity: "legendary",
    effect: "camera",
    description: "Activate a trinket's ablity.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "trinket",
  },
  {
    id: "soap",
    name: "Soap",
    emoji: "🧼",
    rarity: "uncommon",
    effect: "soap",
    description: "Remove a slot from a reel, permanently.",
    kind: "tool",
    maxUses: 4,
    limitedUse: true,
    target: "reel",
  },
  {
    id: "mirror",
    name: "Mirror",
    emoji: "🪞",
    rarity: "legendary",
    effect: "mirror",
    description: "Permanently gain an exact copy of a trinket.",
    kind: "tool",
    maxUses: 1,
    limitedUse: true,
    target: "trinket",
  },
  {
    id: "atm",
    name: "ATM",
    emoji: "🏧",
    rarity: "legendary",
    effect: "atm",
    description:
      "Spend $15 to give another tool one more use this spin. Legendary tools cost $150 to refresh.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "tool",
  },
  {
    id: "lock",
    name: "Lock",
    emoji: "🔒",
    rarity: "uncommon",
    effect: "lock",
    description: "Fix a reel at its current value for the next spin.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "reel",
  },
  {
    id: "qubit",
    name: "Superposition",
    emoji: "🔱",
    rarity: "rare",
    effect: "qubit",
    description:
      "Permanently replace a slot on a reel with a Superposition, which lets you choose between whether it's a zero or a one.",
    kind: "tool",
    maxUses: 2,
    limitedUse: true,
    target: "reel",
  },
  {
    id: "butterfly",
    name: "Butterfly",
    emoji: "🦋",
    rarity: "rare",
    effect: "butterfly",
    description:
      "Permanently change a trinket into another of the same rarity.",
    kind: "tool",
    maxUses: 1,
    limitedUse: false,
    target: "trinket",
  },
  {
    id: "sparkles",
    name: "Sparkles",
    emoji: "✨",
    rarity: "rare",
    effect: "sparkles",
    description:
      "Permanently change a trinket into another with one higher rarity.",
    kind: "tool",
    maxUses: 1,
    limitedUse: true,
    target: "trinket",
  },
  {
    id: "incrementall",
    name: "Increment All",
    emoji: "⏫",
    rarity: "common",
    effect: "incrementall",
    description: "Add 1 to ALL reels (9 becomes 0).",
    kind: "tool",
    maxUses: 2,
    limitedUse: false,
    target: "all",
  },
  {
    id: "decrementall",
    name: "Decrement All",
    emoji: "⏬",
    rarity: "common",
    effect: "decrementall",
    description: "Subtract 1 from ALL reels (0 becomes 9).",
    kind: "tool",
    maxUses: 2,
    limitedUse: false,
    target: "all",
  },
];
export const ITEMS = Object.fromEntries(
  [...TRINKETS, ...TOOLS].map((item) => [item.id, item]),
);

/** Returns an item's custom price, falling back to its rarity's base price. */
export function itemPrice(item) {
  return item.price ?? RARITIES[item.rarity].price;
}

/**
 * Creates an independently mutable owned instance from an item definition.
 * @param {string} id Catalog item identifier.
 * @returns {object} Owned trinket metadata or tool-use state.
 */
export function ownItem(id) {
  const def = ITEMS[id];
  return def.kind === "trinket"
    ? { id, metadata: { ...def.metadata } }
    : { id, maxUses: def.maxUses, uses: def.maxUses };
}

/**
 * Builds the current player-facing description of an owned item.
 * @param {object} owned Owned trinket or tool instance.
 * @returns {string} Description including current power or uses per spin.
 */
export function itemDescription(owned) {
  const def = ITEMS[owned.id];
  return (
    def.description +
    (owned.metadata?.favorite != null
      ? ` Favorite: ${owned.metadata.favorite}.`
      : "") +
    (owned.metadata?.count != null
      ? ` Progress: ${owned.metadata.count}.`
      : "") +
    (owned.metadata?.power != null
      ? ` Current power: ${owned.metadata.power}.`
      : "") +
    (def.kind === "tool"
      ? def.limitedUse
        ? `\n${owned.uses} uses left for this run.`
        : `\n${owned.maxUses ?? def.maxUses} uses per spin.`
      : "")
  );
}

/**
 * Resolves an item's local PNG or OpenMoji SVG asset path.
 * @param {string} id Catalog item identifier.
 * @returns {string} Browser-relative icon path.
 */
export function iconPath(id) {
  if (id === "high") return "openmoji-svg-color/1F636-200D-1F32B-FE0F.svg";
  if (id === "three") return "openmoji-svg-color/0033-FE0F-20E3.svg";
  if (id === "w") return "assets/w.svg";
  if (id === "reroll") return "assets/reroll.png";
  if (id === "even") return "assets/even.png";
  const code = [...ITEMS[id].emoji]
    .filter((c) => c.codePointAt(0) !== 0xfe0f)
    .map((c) => c.codePointAt(0).toString(16).toUpperCase())
    .join("-");
  return `openmoji-svg-color/${code}.svg`;
}
